authors:
  saleh:
    name: محمد صالح ابراهیمی
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/76643021
    url: https://github.com/salehin90
  parisa:
    name: پریسا رضائی
    description: Solutions Architect
    avatar: https://avatars.githubusercontent.com/u/207300412
    url: https://github.com/Parisa-86
  katharinalisalin:
    name: Kathi
    description: Communications
    avatar: https://avatars.githubusercontent.com/u/105352741
    url: https://github.com/katharinalisalin
